// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDejW0uIhWh0V7LOlZ5HpDe4XhG_MXRZJU',
    appId: '1:1032753906565:web:03232416e58164c2557aec',
    messagingSenderId: '1032753906565',
    projectId: 'studentmarket-mit',
    authDomain: 'studentmarket-mit.firebaseapp.com',
    storageBucket: 'studentmarket-mit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjVS-5A9LZGxU68u9un8C8O92244Fkaec',
    appId: '1:1032753906565:android:99b870048f3017e7557aec',
    messagingSenderId: '1032753906565',
    projectId: 'studentmarket-mit',
    storageBucket: 'studentmarket-mit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAujyjquU_Z-UzZztvj3VxaS07vS6PX0y8',
    appId: '1:1032753906565:ios:0069ece12efb47a8557aec',
    messagingSenderId: '1032753906565',
    projectId: 'studentmarket-mit',
    storageBucket: 'studentmarket-mit.firebasestorage.app',
    iosBundleId: 'com.example.devecerskiIt732022',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAujyjquU_Z-UzZztvj3VxaS07vS6PX0y8',
    appId: '1:1032753906565:ios:0069ece12efb47a8557aec',
    messagingSenderId: '1032753906565',
    projectId: 'studentmarket-mit',
    storageBucket: 'studentmarket-mit.firebasestorage.app',
    iosBundleId: 'com.example.devecerskiIt732022',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDejW0uIhWh0V7LOlZ5HpDe4XhG_MXRZJU',
    appId: '1:1032753906565:web:b83212a10b7d7a57557aec',
    messagingSenderId: '1032753906565',
    projectId: 'studentmarket-mit',
    authDomain: 'studentmarket-mit.firebaseapp.com',
    storageBucket: 'studentmarket-mit.firebasestorage.app',
  );
}
